# Generated by Django 6.0.4 on 2026-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeriousDlqin2yrs', models.IntegerField()),
                ('RevolvingUtilizationOfUnsecuredLines', models.FloatField()),
                ('age', models.IntegerField()),
                ('NumberOfTime30_59DaysPastDueNotWorse', models.IntegerField()),
                ('DebtRatio', models.FloatField()),
                ('MonthlyIncome', models.FloatField(blank=True, null=True)),
                ('NumberOfOpenCreditLinesAndLoans', models.IntegerField()),
                ('NumberOfTimes90DaysLate', models.IntegerField()),
                ('NumberRealEstateLoansOrLines', models.IntegerField()),
                ('NumberOfTime60_89DaysPastDueNotWorse', models.IntegerField()),
                ('NumberOfDependents', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
