# Generated by Django 6.0.4 on 2026-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_predicteddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicteddata',
            name='NumberOfOpenCreditLinesAndLoans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='NumberOfTime30_59DaysPastDueNotWorse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='NumberOfTime60_89DaysPastDueNotWorse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='NumberOfTimes90DaysLate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='NumberRealEstateLoansOrLines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='RevolvingUtilizationOfUnsecuredLines',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='SeriousDlqin2yrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
