# Generated by Django 6.0.4 on 2026-04-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_predicteddata_numberofopencreditlinesandloans_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predicteddata',
            old_name='SeriousDlqin2yrs',
            new_name='PredictedSeriousDlqin2yrs',
        ),
    ]
