# Generated by Django 6.0.4 on 2026-04-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_seriousdlqin2yrs_predicteddata_predictedseriousdlqin2yrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predicteddata',
            old_name='PredictedSeriousDlqin2yrs',
            new_name='PredictedSeriousDlqin2yrs_lr',
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='PredictedSeriousDlqin2yrs_rf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='PredictedSeriousDlqin2yrs_xgb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
