# Generated by Django 6.0.4 on 2026-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_predictedseriousdlqin2yrs_predicteddata_predictedseriousdlqin2yrs_lr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicteddata',
            name='id',
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='Id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
