# Generated by Django 6.0.4 on 2026-04-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_predicteddata_id_predicteddata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicteddata',
            name='Id',
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='PredictedDataId',
            field=models.IntegerField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
